version: '2'

services:
    databus:
        extends:
            file: docker-compose.yml
            service: databus
        image: rabbitmq:3-management
        ports:
            - '15673:15672'
